### ISSUE TITLE
Future of this organization

### ISSUE THREAD

**Issue by anoff** [DeveloperRadar/web#3]
Hey Marcus,

I was wondering if you have any plans to continue developing the app you got in this organization.
If not, would you be willing to give up the name and let me re-use the github.com/devradar organization for my project https://github.com/anoff/devradar. It's currently in a mono-repoish state but I want to split it up into multiple repos and therefore wanted to create an org and saw the name is taken.

Cheers, Andreas

**Comment by marcusreaiche** [comment]
Hi Andreas,

No problem. I changed the name of my organization to DeveloperRadar so you can use the devradar name in yours.
Good luck in your project!

Cheers,
Marcus

**Comment by anoff** [comment]
Thanks a lot sir. Gotta love the OSS community 😃
